### ISSUE TITLE
Macbook Bootcamp Windows 10

### ISSUE THREAD

**Issue by tonycompany** [twopointzero/TJAPlayer3#61]
SlimDX.DirectInput.DirectInputException: E_INVALIDARG: An invalid parameter was passed to the returning function (-2147024809)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.DirectInput.Mouse..ctor(DirectInput directInput)
   at FDK.CInputMouse..ctor(IntPtr hWnd, DirectInput directInput) in C:\projects\tjaplayer3\FDK19\コード\02.入力\CInputMouse.cs:line 38
   at FDK.CInput管理..ctor(IntPtr hWnd) in C:\projects\tjaplayer3\FDK19\コード\02.入力\CInput管理.cs:line 65
   at TJAPlayer3.TJAPlayer3.t起動処理() in C:\projects\tjaplayer3\TJAPlayer3\Common\TJAPlayer3.cs:line 1722
   at TJAPlayer3.TJAPlayer3..ctor() in C:\projects\tjaplayer3\TJAPlayer3\Common\TJAPlayer3.cs:line 346
   at TJAPlayer3.Program.MainImpl() in C:\projects\tjaplayer3\TJAPlayer3\Common\Program.cs:line 91
   at TJAPlayer3.ErrorReporting.ErrorReporter.WithErrorReporting(Action action) in C:\projects\tjaplayer3\TJAPlayer3\ErrorReporting\ErrorReporter.cs:line 50

**Comment by twopointzero** [comment]
The error was automatically reported (as indicated to you in the user interface) but thanks for opening an issue here. If you have any further details you wish to provide (as indicated in the GitHub issue template you were shown when first creating this issue) feel free to do so. Mouse users are rare and their errors more rare, so any details you can pass along might be of help.
